#pragma once
#define SCIVIBE_MOUSE_BUTTON_1         0
#define SCIVIBE_MOUSE_BUTTON_2         1
#define SCIVIBE_MOUSE_BUTTON_3         2
#define SCIVIBE_MOUSE_BUTTON_4         3
#define SCIVIBE_MOUSE_BUTTON_5         4
#define SCIVIBE_MOUSE_BUTTON_6         5
#define SCIVIBE_MOUSE_BUTTON_7         6
#define SCIVIBE_MOUSE_BUTTON_8         7
#define SCIVIBE_MOUSE_BUTTON_LAST      SCIVIBE_MOUSE_BUTTON_8
#define SCIVIBE_MOUSE_BUTTON_LEFT      SCIVIBE_MOUSE_BUTTON_1
#define SCIVIBE_MOUSE_BUTTON_RIGHT     SCIVIBE_MOUSE_BUTTON_2
#define SCIVIBE_MOUSE_BUTTON_MIDDLE    SCIVIBE_MOUSE_BUTTON_3